branch-defaults:
  develop:
    environment: habitApiNode-env
environment-defaults:
  habitApiNode-env:
    branch: null
    repository: null
global:
  application_name: habit-api-node
  default_ec2_keyname: habit-api-node-key
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.4.4
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
